apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-deployment
 namespace: exam
 labels:
   app: helloworld
spec:
 replicas: 1
 selector:
   matchLabels:
     app: helloworld
 template:
   metadata:
     labels:
       app: helloworld
   spec:
     containers:
       - name: helloworld
         image: peter3000gt/helloworld
         imagePullPolicy: IfNotPresent